services:
  colbertdb:
    container_name: colbertdb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: dev
    ports:
      - "8080:8080"
    environment:
      - AUTH_MODE=API_KEY
      - DEFAULT_API_KEY=supersecret
      - MANAGEMENT_API_KEY=supersecret
      - SECRET_KEY=supersecret
      - COLBERT_LOAD_TORCH_EXTENSION_VERBOSE=True
    volumes:
      - ./colbertdb:/src/colbertdb
      - ./scripts/warm.py:/src/scripts/warm.py
      - ./.data/:/src/.data/