services:
  colbertdb:
    container_name: colbertdb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=dev
    ports:
      - "8080:8080"

    environment:
      - AUTH_MODE=no_auth
    entrypoint: ["uvicorn", "colbertdb.server.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - ./colbertdb:/src/colbertdb
      - ./.data:/src/.data
